# Generated by Django 5.0.6 on 2025-02-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_pendinguser_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='otp_expires_at',
        ),
    ]
