# Generated by Django 5.1 on 2025-02-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_account_ledger_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
